### ISSUE TITLE
Error retriving images

### ISSUE THREAD

**Issue by fvalle1** [kraftcloud/examples#60]
I am trying to reproduce the python example on macOS

I run

`kraft cloud deploy --metro fra0 .`

this is my kraftfile
```yaml
spec: v0.6

runtime: python:3.12

rootfs: ./Dockerfile

cmd: ["/usr/bin/python3", "/home/pizza_bot.py"]

```

```bash
 E  could not prepare deployment: could not package: could not package: could not find runtime 'index.unikraft.io/official/python:3.12'
```
